name: Deploying

on:
  workflow_dispatch

jobs:
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Deploy
        run: echo "Deployed on Dev environment"

  Stage:
    runs-on: ubuntu-latest
    environment: Stage
    needs: Dev
    steps:
      - name: Deploy
        run: echo "Deployed on Staging environment"

  Prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: Stage
    steps:
      - name: Deploy
        run: echo "Deployed on Production environment"
